## To get all the flights and the available seats on them ...
SELECT F.FLIGHT_NUMBER, F.AIRLINE_NAME, F.DEPARTURE_AIRPORT, F.ARRIVAL_AIRPORT, F.DEPARTURE_DATE, F.DEPARTURE_TIME, 
F.ARRIVAL_TIME, F.FLIGHT_DURATION, F.PRICE, COUNT(S.SEAT_ID) AS AVAILABLE_SEATS
FROM FLIGHT F
INNER JOIN SEAT S ON F.FLIGHT_NUMBER = S.FLIGHT_NUMBER
WHERE S.IS_AVAILABLE = 1
GROUP BY F.FLIGHT_NUMBER
HAVING COUNT(S.SEAT_ID) >= 1;


## Update the seat 1 of flight 1 and set the availability to 1...
UPDATE SEAT
SET IS_AVAILABLE = 0
WHERE SEAT_ID = 1 and SEAT_NUMBER = 1 AND FLIGHT_NUMBER = 1; 