CREATE TABLE FLIGHT (
	FLIGHT_NUMBER INT AUTO_INCREMENT PRIMARY KEY,
    AIRLINE_NAME VARCHAR(100) NOT NULL,
    DEPARTURE_AIRPORT VARCHAR(100) NOT NULL,
    ARRIVAL_AIRPORT VARCHAR(100) NOT NULL,
    DEPARTURE_DATE DATE NOT NULL,
    DEPARTURE_TIME TIME NOT NULL,
    ARRIVAL_TIME TIME NOT NULL,
    FLIGHT_DURATION INT NOT NULL,
    PRICE FLOAT NOT NULL
)