CREATE TABLE PASSENGER (
	PASSENGER_PASSPORT_NUMBER INT NOT NULL PRIMARY KEY,
    NAMEp VARCHAR(100) NOT NULL,
    SURNAMEp VARCHAR(100) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(150) NOT NULL,
    PHONE VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL
);
