CREATE TABLE SEAT (
	SEAT_ID INT AUTO_INCREMENT PRIMARY KEY,
	SEAT_NUMBER INT NOT NULL,
    FLIGHT_NUMBER INT NOT NULL,
    IS_AVAILABLE BOOLEAN NOT NULL,
    CLASS VARCHAR(50) NOT NULL,
    PRICE FLOAT NOT NULL,
   FOREIGN KEY (FLIGHT_NUMBER) REFERENCES FLIGHT(FLIGHT_NUMBER),
   UNIQUE (SEAT_NUMBER, FLIGHT_NUMBER)
)