CREATE TABLE BOOKING (
	BOOKING_NUMBER INT AUTO_INCREMENT PRIMARY KEY,
    BOOKING_DATE DATE NOT NULL,
    PASSENGER_PASSPORT_NUMBER INT NOT NULL,
    FLIGHT_NUMBER INT NOT NULL,
    DEPARTURE_DATE DATE NOT NULL,
    DEPARTURE_TIME TIME NOT NULL,
    ARRIVAL_TIME TIME NOT NULL,
    FOREIGN KEY (PASSENGER_PASSPORT_NUMBER) REFERENCES PASSENGER(PASSENGER_PASSPORT_NUMBER),
    FOREIGN KEY (FLIGHT_NUMBER) REFERENCES FLIGHT(FLIGHT_NUMBER)
)